### ISSUE TITLE
Makefile `test-node` command needs to pass through command line input

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra-v2#58]
I'd like to be able to run one off tests with the `make test-node` command. Right now I had to edit `ops/test-node.sh` to use the following lines to run a single test:

```sh
test_command='
  jest --config ops/jest.config.json --listTests
  jest --config ops/jest.config.json -t "should add multisig"
'
```

Jest does not use the `.only` commands like Mocha (it uses them but only within a single file, still runs the other files).

**Comment by bohendo** [comment]
Ahh I had this problem too.

One problem: `make` doesn't accept extra command line args so we can't append stuff like `-t "should add multisig"` to the end of make commands and have them be passed through.

Pretty easy to do it via bash though eg `bash ops/test-node.sh -t "should add multisig"`. Added this in commit `3213c90` of the `init-daicard` branch I'm working on. It should be ready to merge in the next day or two otherwise you can cherry-pick it to get it sooner.
